export const DEMO_ACCOUNTS = [
  {
    email: 'dispatch@swiftroute.ph',
    password: 'demo2024',
    role: 'dispatcher',
    userId: 'U001',
    name: 'Dispatch Center',
  },
  {
    email: 'marco@swiftroute.ph',
    password: 'demo2024',
    role: 'driver',
    userId: 'U002',
    driverId: 'D001',
    name: 'Marco Santos',
  },
  {
    email: 'liza@swiftroute.ph',
    password: 'demo2024',
    role: 'driver',
    userId: 'U003',
    driverId: 'D004',
    name: 'Liza Torres',
  },
  {
    email: 'ops@techgadgets.ph',
    password: 'demo2024',
    role: 'merchant',
    userId: 'U004',
    merchantId: 'M001',
    name: 'TechGadgets PH',
  },
  {
    email: 'ops@freshfarm.ph',
    password: 'demo2024',
    role: 'merchant',
    userId: 'U005',
    merchantId: 'M002',
    name: 'FreshFarm Co.',
  },
  {
    email: 'ops@stylehub.ph',
    password: 'demo2024',
    role: 'merchant',
    userId: 'U006',
    merchantId: 'M003',
    name: 'StyleHub Manila',
  },
]